# Email Settings
smtp_ip: 10.173.66.124
smtp_port: 25
email_to: insightmail@insight.suez.com,bhavin.gala@suez.com # comma separates list of strings, no spaces
polling_interval: 600 # Time between readings in seconds


# Devices
devices:
  - type: wise4010
  - name: device1 # used for email_subject, filename, and email_from
  - ip: 10.0.0.1' # string

# Devices
devices:
  - type: wise4010
  - name: device2 # used for email_subject, filename, and email_from
  - ip: 10.0.0.2' # string